### ISSUE TITLE
How to configure proxy

### ISSUE THREAD

**Issue by fyn-dev** [deptno/nextjs-typescript-boilerplate#9]
How in this starter kit to setup proxy for api? Which is running on different instance and port. In original JavaScript we have this [solution](https://github.com/zeit/next.js/tree/master/examples/with-custom-reverse-proxy)

But how to setup in this typescript starter kit? Any advice, example, solution?

**Comment by deptno** [comment]
This starter kit uses custom `next.config.js` which is used **next** command(eg, `./node_mobules/.bin/node next start`) for typescript compile process with webpack.

according to <https://github.com/zeit/next.js/#custom-server-and-routing>

proxy setup issue is out of `next` environment, so you can't use **next**'s compile environment.

If you want to setup proxy, basically there are two ways

- write custom server code in js.
- write ts and manually compile to js.

I recommend you the second way. because you need to extra setup(babel) to use es2015+ syntax.
